#!/usr/bin/env node
// 从 data.js 生成 SEO 友好的静态 HTML 列表 + ItemList JSON-LD，
// 注入 index.html 的 <!-- BEGIN:prerender --> ... <!-- END:prerender --> 之间。
// 让 JS 渲染弱的爬虫（Bing / Yandex / Baidu 等）也能完整抓到工具列表。
// Usage: node scripts/prerender.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DATA = resolve(ROOT, 'data.js');
const HTML = resolve(ROOT, 'index.html');

const SITE_NAME = '终端神器';
const SITE_DESC = '现代 CLI / TUI 工具集';

const dataText = readFileSync(DATA, 'utf8');
const dataModuleURL = 'data:text/javascript;base64,' +
  Buffer.from(dataText + '\nexport default CATALOG;').toString('base64');
const { default: CATALOG } = await import(dataModuleURL);

const esc = (s) => String(s ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const items = CATALOG.map((it) => {
  const name = esc(it.name);
  const desc = esc(it.desc?.zh || '');
  const url = esc(it.url || '');
  return `      <li><h3>${name}</h3><p>${desc}</p><a href="${url}" rel="noopener nofollow">${url}</a></li>`;
}).join('\n');

const listHTML = `<section id="ssr-fallback" hidden aria-hidden="true">
  <h2>所有工具完整列表</h2>
  <p>共 ${CATALOG.length} 款现代 CLI / TUI 工具，覆盖系统监控、文件搜索、文本数据处理、网络调试、Docker / Kubernetes、Git、AI 终端、Shell 美化等场景。</p>
  <ol>
${items}
  </ol>
</section>`;

const itemListSchema = {
  '@context': 'https://schema.org',
  '@type': 'ItemList',
  name: `${SITE_NAME} · ${SITE_DESC}`,
  description: `精选 ${CATALOG.length} 款 Rust / Go 实现的现代终端工具。`,
  numberOfItems: CATALOG.length,
  itemListElement: CATALOG.map((it, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    item: {
      '@type': 'SoftwareApplication',
      name: it.name,
      description: it.desc?.zh || '',
      url: it.url,
      applicationCategory: 'DeveloperApplication',
      operatingSystem: 'Linux, macOS, Windows',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
  })),
};

const schemaHTML = `<script type="application/ld+json">
${JSON.stringify(itemListSchema, null, 2)}
</script>`;

const block = `<!-- BEGIN:prerender (auto-generated by scripts/prerender.mjs — do not edit) -->
${listHTML}
${schemaHTML}
<!-- END:prerender -->`;

const html = readFileSync(HTML, 'utf8');
const blockRegex = /<!-- BEGIN:prerender[\s\S]*?<!-- END:prerender -->/;
const next = blockRegex.test(html)
  ? html.replace(blockRegex, block)
  : html.replace(/<\/body>/, `${block}\n</body>`);

if (next === html) {
  console.log('✅ prerender block unchanged');
} else {
  writeFileSync(HTML, next);
  console.log(`✅ prerender → ${CATALOG.length} items injected into index.html`);
}
